// Generate docs/CODE_MAP.md: where every system and every multi-layer function lives.
// usage (from repo root): node tools/test/codemap.js
const fs = require('fs'), path = require('path'), espree = require('espree'), escope = require('eslint-scope');
const G = 'game/scripts';
const out = [];
out.push('# The Forge code map', '', 'Generated by `node tools/test/codemap.js`. Do not edit by hand.', '');
out.push('## How the source is organised', '',
 '* `game/page.html` holds the HTML. `game/styles/` holds the CSS.',
 '* `game/scripts/main/` holds all game code. The build joins the files in name order into **one strict script**.',
 '  * `00-header.js`: the "use strict" line and a few global names.',
 '  * `1x-<system>.js`: every function declaration, grouped by system (guild, mine, shop, compendium, quests, skills, save, audio, forge, items, combat, ui, playtest, misc). Function declarations are hoisted, so the order of these files does not matter.',
 '  * `5xx-setup-*.js`: everything that must run in order when the page loads: constant data, the remaining patch layers (`X = function(){ ... }` that extend an earlier version), and start-up code. **The order of these files and of the statements inside them matters.**',
 '* Some functions are split into named steps. For example `function renderTownBase()` is extended by the next function in the same file, which calls it. The comment "Earlier version of X()" marks these.',
 '* `mobile.*` and `landscape.*` (repo root) are the phone layers, loaded after the game.', '',
 '## Rules for changes', '',
 '1. Change a function where it lives. Do not add new wrapper layers (`const old = f; f = function(){ old(); ... }`). Edit the function instead.',
 '2. New functions go in the matching system file. Start-up code goes at the end of the last setup file.',
 '3. After any change run `python3 tools/build.py`, then `bash tools/test/regress.sh`. Intentional gameplay changes will show up as differences. Check that only what you meant changed, then refresh the reference with `python3 tools/build.py --reference`.', '');
const folders = fs.readdirSync(G).sort();
const files = []; // {folder, file, start, end}
out.push('## Files', '', '| File | Size | Starts with |', '|---|---|---|');
for (const f of folders) {
  let pos = 0; const d = path.join(G, f);
  for (const file of fs.readdirSync(d).sort()) {
    const txt = fs.readFileSync(path.join(d, file), 'utf8');
    files.push({folder: f, file, start: pos, end: pos + txt.length, txt});
    const first = (txt.trim().split('\n')[0] || '').replace(/\|/g, '/').slice(0, 90);
    out.push(`| ${f}/${file} | ${(txt.length / 1024).toFixed(0)} KB | ${first} |`);
    pos += txt.length;
  }
}
// layers per global function
const layers = {};
for (const f of folders) {
  const parts = files.filter(x => x.folder === f); const src = parts.map(p => p.txt).join('');
  const ast = espree.parse(src, {ecmaVersion: 'latest', range: true});
  const sm = escope.analyze(ast, {ecmaVersion: 2022});
  const where = off => { const p = parts.find(p => off >= p.start && off < p.end); const line = src.slice(p.start, off).split('\n').length; return `${f}/${p.file}:${line}`; };
  const g = sm.globalScope;
  g.variables.forEach(v => v.defs.forEach(d => { if (d.type === 'FunctionName' && d.node.type === 'FunctionDeclaration') (layers[v.name] = layers[v.name] || []).push(where(d.node.range[0])); }));
  const refs = []; g.variables.forEach(v => v.references.forEach(r => refs.push(r))); g.through.forEach(r => refs.push(r));
  refs.forEach(r => { if (!r.isWrite()) return; const id = r.identifier; const par = r.writeExpr;
    if (par && /Function/.test(par.type)) (layers[id.name] = layers[id.name] || []).push(where(id.range[0])); });
}
const multi = Object.entries(layers).filter(([, v]) => v.length > 1).sort((a, b) => b[1].length - a[1].length);
out.push('', '## Functions built from several layers', '', `${multi.length} functions. Layers are listed in the order they run their setup (first = base version).`, '');
for (const [name, locs] of multi) out.push(`* **${name}** (${locs.length}): ` + locs.map(l => '`' + l + '`').join(', '));
fs.mkdirSync('docs', {recursive: true});
fs.writeFileSync('docs/CODE_MAP.md', out.join('\n') + '\n');
console.log('functions with layers:', multi.length, 'total layers:', multi.reduce((s, [, v]) => s + v.length, 0));
