/* The Forge offline worker. Generated by build.py; version 1beb1a84d0 */
const CACHE = "forge-1beb1a84d0";
const FILES = [
 "./",
 "index.html",
 "mobile.css?v=1beb1a84d0",
 "mobile.js?v=1beb1a84d0",
 "landscape.css?v=1beb1a84d0",
 "landscape.js?v=1beb1a84d0",
 "manifest.webmanifest",
 "icons/apple-touch-icon.png",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-maskable-512.png",
 "audio/musDjartV50.mp3",
 "audio/musInonoV50.mp3",
 "audio/musMoodV50.mp3"
];

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith("forge-") && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return;
  // The game page: try the network first so updates arrive, fall back to the offline copy
  if (req.mode === "navigate") {
    e.respondWith(fetch(req).then(r => {
      const copy = r.clone(); caches.open(CACHE).then(c => c.put("index.html", copy)); return r;
    }).catch(() => caches.match("index.html", {ignoreSearch: true})));
    return;
  }
  // Everything else (music, icons, scripts): offline copy first
  e.respondWith(caches.match(req).then(hit => hit || fetch(req)));
});
